-- The Ministry Games
-- Server-authoritative game tables. Public clients do not receive direct table access.
-- Run on the SAME Supabase project used by theministry.vercel.app.

create extension if not exists pgcrypto;

create table if not exists public.game_sessions (
  id uuid primary key default gen_random_uuid(),
  game_code text not null unique,
  status text not null default 'lobby',
  version bigint not null default 1,
  host_token_hash text not null,
  display_token_hash text,
  state jsonb not null default '{}'::jsonb,
  question_pack jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ended_at timestamptz
);

create index if not exists game_sessions_code_idx on public.game_sessions(game_code);
create index if not exists game_sessions_status_idx on public.game_sessions(status);
create index if not exists game_sessions_updated_at_idx on public.game_sessions(updated_at desc);

create table if not exists public.game_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.game_sessions(id) on delete cascade,
  player_id text not null,
  token_hash text not null,
  name text not null,
  team_id text not null,
  is_captain boolean not null default false,
  connected boolean not null default true,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(game_id, player_id)
);

create index if not exists game_players_game_idx on public.game_players(game_id);
create index if not exists game_players_team_idx on public.game_players(game_id, team_id);
create index if not exists game_players_connected_idx on public.game_players(game_id, connected);

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.game_sessions(id) on delete cascade,
  game_code text not null,
  kind text not null,
  actor_type text not null default 'system',
  player_id text,
  team_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists game_events_game_idx on public.game_events(game_id, id desc);
create index if not exists game_events_code_idx on public.game_events(game_code, id desc);
create index if not exists game_events_kind_idx on public.game_events(kind, created_at desc);

alter table public.game_sessions enable row level security;
alter table public.game_players enable row level security;
alter table public.game_events enable row level security;

-- No anon/authenticated policies on these tables by design.
-- All mutations and reads go through Vercel server functions using a Supabase secret/service key.
-- This prevents clients from reading answer keys or forging scores.

create or replace function public.touch_game_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  new.version = old.version + 1;
  return new;
end;
$$;

drop trigger if exists game_sessions_touch on public.game_sessions;
create trigger game_sessions_touch
before update on public.game_sessions
for each row execute function public.touch_game_updated_at();


create table if not exists public.game_submissions (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.game_sessions(id) on delete cascade,
  game_code text not null,
  question_id text not null,
  player_id text not null,
  team_id text not null,
  answer text not null,
  is_captain boolean not null default false,
  created_at timestamptz not null default now(),
  unique(game_id, question_id, player_id)
);

create index if not exists game_submissions_question_idx
  on public.game_submissions(game_id, question_id, created_at asc);
create index if not exists game_submissions_team_idx
  on public.game_submissions(game_id, question_id, team_id, created_at asc);

alter table public.game_submissions enable row level security;
