const C=document.querySelector('#builderContent'),tabs=[...document.querySelectorAll('.tab')],w1=window.KE11_EVIDENCE||{},w2=window.KE11_WEEK2||{};const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const slideCards=()=>[...(w1.SLIDES||[]).map((s,i)=>({...s,week:1,n:i+1})),...(w2.SLIDES||[]).map((s,i)=>({...s,week:2,n:i+1}))].map(s=>`<article class="content-row"><span class="index">W${s.week} · ${s.n}</span><div><strong>${esc(s.title||s.ref||s.kicker)}</strong><small>${esc(s.kicker||s.type)}</small></div></article>`).join('');
const scripture=()=>[...(w1.VERSES||[]),...(w2.VERSES||[])].map(v=>`<article class="scripture-row"><strong>${esc(v.ref)}</strong><p>${esc(v.text)}</p></article>`).join('');
const polls=()=>[...(w1.POLLS||[]),...(w2.POLLS||[])].map(p=>`<article class="card"><span class="tag">POLL</span><h3>${esc(p.question)}</h3><p>${(p.options||[]).map(esc).join(' · ')}</p></article>`).join('');
function render(k){tabs.forEach(t=>t.classList.toggle('active',t.dataset.tab===k));const views={
overview:`<div class="panel-head"><div><p class="eyebrow">MODULE OVERVIEW</p><h1>Matthew 11</h1><p class="lede">Questioning → Offense → Rejection → Accountability → Revelation → Rest</p></div><a class="button" href="/evidence/">Student view</a></div><div class="stat-grid"><div><strong>${(w1.SLIDES||[]).length+(w2.SLIDES||[]).length}</strong><span>Slides</span></div><div><strong>${(w1.VERSES||[]).length+(w2.VERSES||[]).length}</strong><span>Scriptures</span></div><div><strong>${(w1.POLLS||[]).length+(w2.POLLS||[]).length}</strong><span>Polls</span></div><div><strong>2</strong><span>Sessions</span></div></div><section class="card"><span class="tag">TEACHING ARC</span><h2>One module, two live sessions</h2><p>Week 1 covers Matthew 11:1–19. Week 2 covers Matthew 11:20–30. Lumaneer treats them as one chapter module while preserving each presentation deck.</p></section>`,
manuscript:`<div class="panel-head"><div><p class="eyebrow">MANUSCRIPT</p><h1>Teacher notes</h1></div><div class="actions"><button class="button" id="loadDeck">Build from current deck</button><button class="button primary" id="saveManuscript">Save draft</button></div></div><section class="card"><h2>Canonical teaching manuscript</h2><p>One source for your teaching, study material, quizzes, slides and AI tools.</p><textarea id="manuscriptText" class="notes-area editor-area" placeholder="Paste or write your teaching manuscript here…"></textarea><small id="editorState" class="muted"></small></section><div class="content-list">${[...(w1.SLIDES||[]),...(w2.SLIDES||[])].filter(s=>s.notes).map(s=>`<article class="content-row"><div><strong>${esc(s.title||s.ref||s.kicker)}</strong><small>${esc(s.notes)}</small></div></article>`).join('')}</div>`,
study:`<div class="panel-head"><div><p class="eyebrow">STUDY GUIDE</p><h1>Student preparation</h1></div><button class="button primary ai-btn" data-ai="study_guide">Generate from manuscript</button></div><section class="card"><h2>Matthew 11 Study Guide</h2><div id="aiOutput" class="generated">Generate a student-facing guide from the canonical manuscript, then edit before publishing.</div></section>`,
slides:`<div class="panel-head"><div><p class="eyebrow">SLIDES</p><h1>Presentation deck</h1></div><a class="button primary" href="/evidence/presenter">Open Presenter</a></div><div class="content-list">${slideCards()}</div>`,
scripture:`<div class="panel-head"><div><p class="eyebrow">SCRIPTURE BANK</p><h1>Matthew 11 references</h1></div><button class="button">+ Scripture</button></div><div class="scripture-list">${scripture()}</div>`,
polls:`<div class="panel-head"><div><p class="eyebrow">LIVE ENGAGEMENT</p><h1>Polls</h1></div><button class="button">+ Poll</button></div><div class="adminnav">${polls()}</div>`,
discussion:`<div class="panel-head"><div><p class="eyebrow">DISCUSSION</p><h1>Module conversation</h1></div><button class="button primary ai-btn" data-ai="discussion">Generate prompts</button></div><section class="card"><h2>Discussion Builder</h2><div id="aiOutput" class="generated">Generate discussion prompts grounded in your manuscript.</div></section>`,
quiz:`<div class="panel-head"><div><p class="eyebrow">ASSESSMENT</p><h1>Quiz & Review</h1></div><button class="button primary ai-btn" data-ai="quiz">Generate Question Bank</button></div><div class="stat-grid"><div><strong>Individual</strong><span>Assessment</span></div><div><strong>Team</strong><span>Class mode</span></div><div><strong>Review</strong><span>Explanations</span></div><div><strong>Live</strong><span>Project results</span></div></div><section class="card"><h2>Shared question bank</h2><p>Questions can power individual quizzes, team rounds and live review without duplicating content.</p></section>`,
resources:`<div class="panel-head"><div><p class="eyebrow">RESOURCES</p><h1>Module library</h1></div><button class="button">+ Resource</button></div><section class="empty">Handouts, PDFs, links, recordings and supplemental reading will live here.</section>`,
live:`<div class="panel-head"><div><p class="eyebrow">LIVE CLASS</p><h1>Teach Matthew 11</h1></div></div><div class="live-launch"><a class="launch" href="/evidence/presenter"><span>TEACHER</span><strong>Launch Presenter</strong><small>Control slides, polls and live teaching.</small></a><a class="launch" href="/evidence/"><span>STUDENT</span><strong>Open Student Room</strong><small>Preview the current participant experience.</small></a><a class="launch" href="/projector"><span>OUTPUT</span><strong>Open Projector</strong><small>Launch the existing presentation output.</small></a></div>`};C.innerHTML=views[k]||views.overview;afterRender(k)}
tabs.forEach(t=>t.onclick=()=>render(t.dataset.tab));render('overview');
function afterRender(k){const E=window.LumaneerEditor;if(!E)return;if(k==='manuscript'){const ta=document.querySelector('#manuscriptText'),saved=E.load();ta.value=saved.manuscript||'';document.querySelector('#loadDeck').onclick=()=>{ta.value=E.manuscriptFromDeck(w1,w2);document.querySelector('#editorState').textContent='Loaded current Chapter 11 teaching notes. Review, then save.'};document.querySelector('#saveManuscript').onclick=()=>{E.save({manuscript:ta.value});document.querySelector('#editorState').textContent='Draft saved.'}}document.querySelectorAll('.ai-btn').forEach(btn=>btn.onclick=async()=>{const out=document.querySelector('#aiOutput')||document.querySelector('.card:last-child');const source=E.load().manuscript||E.manuscriptFromDeck(w1,w2);btn.disabled=true;btn.textContent='Generating…';try{const result=await E.ai(btn.dataset.ai,source);if(out){out.textContent=result;out.classList.add('generated-ready')}E.save({[btn.dataset.ai]:result})}catch(e){if(out)out.textContent=e.message}finally{btn.disabled=false;btn.textContent=btn.dataset.ai==='quiz'?'Generate Question Bank':btn.dataset.ai==='discussion'?'Generate prompts':'Generate from manuscript'}})}
